In [92]:
import pandas as pd
import glob
import math
from decimal import Decimal

In [2]:
df = pd.DataFrame()
for report in glob.glob('new_report*'):
    if df.empty:
        df = pd.read_csv(report)
    else:
        df = pd.concat([pd.read_csv(report), df])
df.drop(columns=['Unnamed: 0'], inplace=True)

In [3]:
df.head()

,word,average/std,percent_average,percent_std,rating,word_count,divisor,percent,time
0,caylus,4.023446,0.00103,0.000256,NaN,NaN,NaN,NaN,2.294487
1,caylus,NaN,NaN,NaN,1.0,1.0,2177.0,0.000459,NaN
2,caylus,NaN,NaN,NaN,2.0,5.0,4527.0,0.001104,NaN
3,caylus,NaN,NaN,NaN,3.0,7.0,8567.0,0.000817,NaN
4,caylus,NaN,NaN,NaN,4.0,13.0,15584.0,0.000834,NaN

In [4]:
df.rename(columns={'average/std': 'average_std'}, inplace=True)

In [145]:
df.to_csv('data.csv')

In [6]:
best_dict = dict(zip(df[['word', 'average_std']].dropna().loc[df.average_std.dropna()<1]['word'], df[['word', 'average_std']].dropna().loc[df.average_std.dropna()<1]['average_std']))

In [7]:
sortedDict=sorted(best_dict.values())
sorted_dict = dict()
for sortedKey in sortedDict:
    for key, value in best_dict.items():
        if value==sortedKey:
            sorted_dict[key]=value

In [14]:
list(sorted_dict.keys())

['smjj',
 'splendid',
 'affair',
 'therefore',
 'p',
 'perfection',
 'gw',
 'irrelevant',
 'loathe',
 'flawless',
 'reviews',
 'flipping',
 'directions',
 'queen',
 'garbage',
 'reliant',
 'all-time',
 'ambition',
 'vote',
 '1010',
 'masterpiece',
 'estimate',
 'worst',
 'magnificent',
 'ts',
 'proud',
 'starstarstarstarnostar',
 'tournaments',
 'phenomenal',
 'crap',
 'watching',
 'awsome',
 'marvelous',
 'wonderfull',
 'piece',
 'rip',
 'moor',
 'outstanding',
 'favs',
 '85',
 'torture',
 'north',
 'bleh',
 'glorious',
 'screaming',
 'unplayable',
 'tuscany',
 'trash',
 'destroy',
 'skydrive',
 'jansma',
 'incredible',
 'legion',
 'spies',
 'naqala',
 'favourites',
 'force',
 'awesomeness',
 'greatest',
 'kmc',
 'amazing',
 'hate',
 'summary',
 'candyland',
 'description',
 'achat',
 'addicted',
 'sent',
 'filling',
 'property',
 'nowhere',
 'waste',
 'premium',
 'ashley',
 'superb',
 'todd',
 '910',
 'avoiding',
 'paranoia',
 'deepest',
 'adapt',
 're-playable',
 'omg',
 'excelent',
 'cracking',
 'borg',
 'lowest',
 'strike',
 'fantastic',
 'blew',
 'brilliance',
 'favorites',
 'underwhelmed',
 'addicting',
 'yuck',
 'coin',
 'perfect',
 'season',
 '95',
 'strain',
 'bash',
 'allowance',
 'reading',
 'purest',
 'hated',
 'treat',
 'pantheon',
 'provoking',
 'fantastically',
 'versatile',
 'meaningless',
 'voters',
 'â€¢',
 'diseases',
 "'take",
 'luckfest',
 'awful',
 'brilliant',
 'ugly',
 'talked',
 'horrible',
 'thankfully',
 'cog',
 'rebel',
 'cdg',
 'according',
 'obsession',
 'burn',
 'genius',
 'thanks',
 'skip',
 'wind',
 '234',
 'plants',
 'partnership',
 'paint',
 "wizard's",
 'unlimited',
 'industry',
 'spin',
 'meet',
 'shit',
 'rocks',
 'must-have',
 'joke',
 'cranium',
 'colony',
 'favorite',
 'remake',
 'approved',
 'produce',
 'dive',
 'organizer',
 'ugh',
 'immersive',
 'forsaken',
 'realms',
 'unlucky',
 "game'",
 'excuse',
 'battleship',
 'adore',
 'oozes',
 'card-based',
 'stupid',
 '0',
 'csi',
 'bottom',
 'eric',
 'describe',
 'awesome',
 'mice',
 'loves',
 'dripping',
 'favourite',
 'delicious',
 'ruins',
 'thousands',
 'inn',
 'wasted',
 'finest',
 'unlikely',
 'mark',
 'ex',
 'tremendously',
 'fav',
 'indifferent',
 'platinum',
 'panasia',
 'guaranteed',
 'dunwich',
 'asymmetry',
 'engrossing',
 'wonderful',
 'street',
 'infinite',
 'greats',
 'prosperity',
 'horribly',
 'express',
 'rubbish',
 'whatsoever',
 'oop',
 'described',
 'sucked',
 'mounted',
 'terrific',
 'pleaser',
 'abbey',
 'morbid',
 'average',
 'shoot',
 'tremendous',
 'wonderfully',
 'clearance',
 'refuse',
 'addiction',
 'unnecessarily',
 'doesn039t',
 'balderdash',
 'jackson',
 'bio-terrorist',
 'sucks',
 'incursion',
 'month',
 'hooked',
 'asymmetrical',
 'arrived',
 '33',
 '710',
 'timeless',
 'wondering',
 'attraction',
 'inoffensive',
 'childish',
 'nonsense',
 'family-friendly',
 'ripper',
 'winloss',
 'brilliantly',
 'fail',
 'cloud',
 'petri',
 'diversion',
 'society',
 'seaside',
 'pile',
 'metro',
 'penguins',
 'sneaky',
 'desire',
 'seat',
 'tracker',
 "family's",
 'alternatives',
 'artisans',
 'turning',
 'bronze',
 'convoluted',
 'handles',
 'terrible',
 '2210',
 'harsh',
 'excite',
 'bloated',
 'blend',
 'yawn',
 'fabulous',
 'intimidating',
 'silliness',
 '27',
 'named',
 'peschong',
 'shock',
 "feld's",
 'lab',
 'pimped',
 'mb',
 'pointless',
 'greatness',
 'exceptions',
 'releases',
 'uninteresting',
 'instantly',
 'jokes',
 'boxed',
 'deserving',
 'deceptively',
 'rails',
 'tied',
 'pig',
 'garfield',
 'absolute',
 'swan',
 'relics',
 '3-7',
 'elegantly',
 'obscure',
 'fluxx',
 'netrunner',
 'unsatisfying',
 'tool',
 'slog',
 'footprint',
 'loving',
 'customization',
 'destinations',
 'tolkien',
 'freaking',
 '2-4p',
 'so-so',
 'hundreds',
 'reduced',
 'earn',
 'shattered',
 'surplus',
 'immediate',
 'sim',
 'bother',
 'painfully',
 'crappy',
 '-limited',
 'youtube',
 'balances',
 'dream',
 'soulless',
 'machine',
 'scalable',
 'bores',
 'et',
 'arguably',
 "daughter's",
 'extensions',
 'excellent',
 'âœ”',
 'recollection',
 'gmt',
 'portion',
 'addictive',
 'bioterrorist',
 'tire',
 'costs',
 'send',
 'mystica',
 'memorize',
 'prepare',
 'solved',
 'blast',
 'bamboo',
 'rising',
 'barely',
 'obsessed',
 'brink',
 'climate',
 'exhausting',
 'veterans',
 'tedious',
 '4-8',
 'styles',
 'uninspired',
 'over-rated',
 '1910',
 'meh',
 'dumb',
 'calculate',
 'jenga',
 'jambo',
 'stopped',
 'lightly',
 'tinmen',
 'walk',
 'expo',
 'worse',
 'disappoint',
 'dicefest',
 'unclear',
 'boredom',
 'tribes',
 'forgot',
 'rolled',
 'heck',
 'search',
 'luster',
 'angry',
 'god',
 'garage',
 'customizable',
 'offensive',
 'flip',
 'pleasantly',
 'instant',
 'uneven',
 'toys',
 'penguin',
 'flexible',
 'light-weight',
 'forgettable',
 'pursuit',
 'collectors',
 'bore',
 'recognize',
 'deserve',
 'eating',
 'accommodate',
 'suspenseful',
 'ratings',
 'painful',
 'colonies',
 'ridiculous',
 'isnt',
 'run',
 'glass',
 'decennial',
 'skullport',
 'bexpansionsb',
 'alike',
 'trilogy',
 'qwirkle',
 'scales',
 'tiresome',
 'mt',
 'set-collection',
 'faction',
 '1-5',
 'scoundrels',
 'bagged',
 'k',
 'awaiting',
 'carbon',
 'forced',
 'jump',
 'mat',
 'alright',
 'properties',
 'excellently',
 'literally',
 'regret',
 'dealt',
 'jason',
 '75',
 'skirmish',
 'na',
 '4x',
 'closest',
 '9',
 'buttons',
 'tentative',
 'roll-and-move',
 'incan',
 'survival',
 'strangers']

In [17]:
df.loc[df.word == 'meaningless']

,word,average_std,percent_average,percent_std,rating,word_count,divisor,percent,time
1628,meaningless,0.772116,0.000666,0.000862,NaN,NaN,NaN,NaN,2.009985
1629,meaningless,NaN,NaN,NaN,1.0,6.0,2177.0,0.002756,NaN
1630,meaningless,NaN,NaN,NaN,2.0,7.0,4527.0,0.001546,NaN
1631,meaningless,NaN,NaN,NaN,3.0,10.0,8567.0,0.001167,NaN
1632,meaningless,NaN,NaN,NaN,4.0,10.0,15584.0,0.000642,NaN
1633,meaningless,NaN,NaN,NaN,5.0,5.0,29081.0,0.000172,NaN
1634,meaningless,NaN,NaN,NaN,6.0,16.0,61091.0,0.000262,NaN
1635,meaningless,NaN,NaN,NaN,7.0,6.0,113108.0,0.000053,NaN
1636,meaningless,NaN,NaN,NaN,8.0,2.0,125466.0,0.000016,NaN
1637,meaningless,NaN,NaN,NaN,9.0,1.0,70468.0,0.000014,NaN
1638,meaningless,NaN,NaN,NaN,10.0,1.0,35426.0,0.000028,NaN

In [12]:
df.loc[df.word == 'hate']

,word,average_std,percent_average,percent_std,rating,word_count,divisor,percent,time
660,hate,0.69701,0.018206,0.02612,NaN,NaN,NaN,NaN,2.043586
661,hate,NaN,NaN,NaN,1.0,189.0,2177.0,0.086817,NaN
662,hate,NaN,NaN,NaN,2.0,203.0,4527.0,0.044842,NaN
663,hate,NaN,NaN,NaN,3.0,168.0,8567.0,0.019610,NaN
664,hate,NaN,NaN,NaN,4.0,178.0,15584.0,0.011422,NaN
665,hate,NaN,NaN,NaN,5.0,174.0,29081.0,0.005983,NaN
666,hate,NaN,NaN,NaN,6.0,241.0,61091.0,0.003945,NaN
667,hate,NaN,NaN,NaN,7.0,319.0,113108.0,0.002820,NaN
668,hate,NaN,NaN,NaN,8.0,303.0,125466.0,0.002415,NaN
669,hate,NaN,NaN,NaN,9.0,151.0,70468.0,0.002143,NaN
670,hate,NaN,NaN,NaN,10.0,73.0,35426.0,0.002061,NaN

In [13]:
df.word.nunique()

4647

In [137]:
def find_higest_power(series):
    higest = 100
    for x in series:
        if not math.isnan(x):
            if higest > int(str('%.2E' % Decimal(x)).split('E')[1][1:3]):
                if 0 != int(str('%.2E' % Decimal(x)).split('E')[1][1:3]):
                    higest = int(str('%.2E' % Decimal(x)).split('E')[1][1:3])
    how_many_are_zero = 0
    for x in series:
        if not math.isnan(x):
            if 0 == int(str('%.2E' % Decimal(x)).split('E')[1][1:3]):
                how_many_are_zero += 1
    if how_many_are_zero > 5:
        print(series.name)
#     return higest, how_many_are_zero

In [138]:
test_df = df.copy()

In [139]:
test_df.groupby('word').percent.apply(find_higest_power)

ambition
favs
jansma
magnificent
skydrive
smjj
strain

word
'             None
'44           None
'em           None
'nuff         None
'take         None
'the          None
-             None
--            None
---           None
----          None
-1            None
-limited      None
0             None
01            None
05            None
09            None
1             None
1-2           None
1-4           None
1-5           None
1-6           None
1-8           None
10            None
10-15         None
100           None
1000          None
1010          None
10th          None
11            None
110           None
              ...
york          None
you           None
you'd         None
you'll        None
you're        None
you've        None
young         None
younger       None
youngest      None
your          None
yourself      None
youth         None
youtube       None
yr            None
yucata        None
yucatade      None
yuck          None
z-man         None
zen           None
zero          None
zombicide     None
zombie        None
zombies       None
zoo           None
zooloretto    None
â€“             None
â€”             None
â€¢             None
âˆ’             None
âœ”             None
Name: percent, Length: 4647, dtype: object

In [144]:
test_df.loc[test_df.word == "zooloretto"]

,word,average_std,percent_average,percent_std,rating,word_count,divisor,percent,time
473,zooloretto,1.202997,0.000232,0.000193,NaN,NaN,NaN,NaN,2.101855
474,zooloretto,NaN,NaN,NaN,1.0,0.0,2177.0,0.000000,NaN
475,zooloretto,NaN,NaN,NaN,2.0,0.0,4527.0,0.000000,NaN
476,zooloretto,NaN,NaN,NaN,3.0,1.0,8567.0,0.000117,NaN
477,zooloretto,NaN,NaN,NaN,4.0,7.0,15584.0,0.000449,NaN
478,zooloretto,NaN,NaN,NaN,5.0,11.0,29081.0,0.000378,NaN
479,zooloretto,NaN,NaN,NaN,6.0,26.0,61091.0,0.000426,NaN
480,zooloretto,NaN,NaN,NaN,7.0,58.0,113108.0,0.000513,NaN
481,zooloretto,NaN,NaN,NaN,8.0,37.0,125466.0,0.000295,NaN
482,zooloretto,NaN,NaN,NaN,9.0,10.0,70468.0,0.000142,NaN
483,zooloretto,NaN,NaN,NaN,10.0,0.0,35426.0,0.000000,NaN