In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import time
import operator
from collections import Counter
from operator import itemgetter
import time as tm
import string

In [3]:
%%time
df_large = pd.read_csv('../data/large_sample.csv')
df_large.drop(columns=['Unnamed: 0'], inplace=True)
df_large.rating = np.ceil(df_large.rating)

CPU times: user 5.09 s, sys: 630 ms, total: 5.72 s
Wall time: 6.49 s

In [4]:
def remove_punctuation(comment):
    table = str.maketrans(dict.fromkeys('@#$%^&*()_+=~`[{}]|\:;"<,>."/'))
    return comment.translate(table)

In [5]:
def replace_exclimation(comment):
    return comment.replace('!', ' <!> ').replace('?', ' <?> ')

In [6]:
%%time
df_large['remove_punctuation'] = df_large.comment.apply(lambda x: remove_punctuation(x))
df_large.drop(columns=['comment'], inplace=True)
df_large.rename(columns={'remove_punctuation':'comment'}, inplace=True)
df_large['replace_punctuation'] = df_large.comment.apply(lambda x: replace_exclimation(x))
df_large.drop(columns=['comment'], inplace=True)
df_large.rename(columns={'replace_punctuation':'comment'}, inplace=True)

CPU times: user 17.3 s, sys: 570 ms, total: 17.9 s
Wall time: 22.8 s

In [7]:
def make_it_lower(comment):
    new_comment = []
    for x in comment.split(' '):
        new_comment.append(x.lower())
    return ' '.join(new_comment)

In [9]:
%%time
df_large['lower_comment'] = df_large.comment.apply(lambda x: make_it_lower(x))
df_large.drop(columns=['comment'], inplace=True)
df_large.rename(columns={'lower_comment':'comment'}, inplace=True)

CPU times: user 20.9 s, sys: 507 ms, total: 21.4 s
Wall time: 27.1 s

In [10]:
def create_count(comment):
    for x in comment.split(' '):
        if x in di:
            di[x] += 1
        else:
            di[x] = 1
    return di

In [13]:
%%time
di = dict()
df_large.loc[df_large.rating == 1].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
one_dict = di
di = dict()
df_large.loc[df_large.rating == 2].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
two_dict = di
di = dict()
df_large.loc[df_large.rating == 3].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
three_dict = di
di = dict()
df_large.loc[df_large.rating == 4].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
four_dict = di
di = dict()
df_large.loc[df_large.rating == 5].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
five_dict = di
di = dict()
df_large.loc[df_large.rating == 6].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
six_dict = di
di = dict()
df_large.loc[df_large.rating == 7].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
seven_dict = di
di = dict()
df_large.loc[df_large.rating == 8].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
eight_dict = di
di = dict()
df_large.loc[df_large.rating == 9].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
nine_dict = di
di = dict()
df_large.loc[df_large.rating == 10].loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].comment.apply(create_count)
ten_dict = di
time = '37s'

CPU times: user 54.3 s, sys: 648 ms, total: 54.9 s
Wall time: 1min 4s

In [14]:
%%time
one_counter = Counter(one_dict)
two_counter = Counter(two_dict)
three_counter = Counter(three_dict)
four_counter = Counter(four_dict)
five_counter = Counter(five_dict)
six_counter = Counter(six_dict)
seven_counter = Counter(seven_dict)
eight_counter = Counter(eight_dict)
nine_counter = Counter(nine_dict)
ten_counter = Counter(ten_dict)

CPU times: user 23.4 ms, sys: 6.11 ms, total: 29.5 ms
Wall time: 35.2 ms

In [15]:
all_counter = one_counter + two_counter + three_counter + four_counter + five_counter + six_counter + seven_counter + eight_counter + nine_counter + ten_counter

In [16]:
all_dict = dict(Counter(all_counter))

In [17]:
%%time
new_data = {k: v for k, v in all_dict.items() if v > 50}

CPU times: user 15.6 ms, sys: 269 µs, total: 15.9 ms
Wall time: 16.3 ms

In [18]:
%%time
sortedList=sorted(new_data.values())
sorted_dict = dict()
for sortedKey in sortedList:
    for key, value in new_data.items():
        if value==sortedKey:
            sorted_dict[key]=value
            
time = '1min 32sec'

CPU times: user 5.6 s, sys: 44.4 ms, total: 5.64 s
Wall time: 8.6 s

In [19]:
%%time
dict_list = []
for key, value in sorted_dict.items():
    temp = [key,value]
    dict_list.append(temp)

CPU times: user 52.4 ms, sys: 17.3 ms, total: 69.7 ms
Wall time: 81.6 ms

In [20]:
testing_df = df_large.loc[df_large.comment.apply(lambda x: len(x.split(' ')))<30].copy()

In [21]:
def word_count(comment, word, number):
    if word in comment.split(' '):
        if word in number:
            number[word] += comment.split(' ').count(word)
        else:
            number[word] = comment.split(' ').count(word)

In [29]:
%%time
def make_report(w, z, dictionary, dataframe):
    dict_list = dictionary
    testing_df = dataframe.copy()
    labels = ['word', 'average/std', 'percent_average', 'percent_std', 'rating', 'word_count', 'divisor', 'percent', 'time']
    to_return = pd.DataFrame(columns=labels)
    for word in dict_list[int(w):int(z)]:
        start_time = tm.time()
        to_append = []
        std = 0
        average = 0
        for y in range(1,11):
            number = dict()
            testing_df.loc[testing_df.rating == y].comment.apply(word_count, word=word[0], number=number)
            divisor = testing_df.loc[testing_df.rating == y].comment.count()
            if word[0] in number:
                percent = number[word[0]]/divisor
            else:
                percent = 0
                number[word[0]] = 0
            to_append.append([word[0], None, None, None, y, number[word[0]], divisor, percent, None])
        for_array = []
        for value in to_append:
            for_array.append(value[7])
        x = np.array(for_array)
        array1 = [[word[0], (np.sum(x)/10)/(np.std(x)), np.sum(x)/10, np.std(x), None, None, None, None, tm.time()-start_time]]
        for x in to_append:
            array1.append(x)
        inbetween_df = pd.DataFrame.from_records(array1, columns=labels)
        to_return = pd.concat([to_return, inbetween_df])
    return to_return

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 15 µs

In [30]:
len(dict_list)

4671

In [31]:
%%time
report = make_report(0,100, dict_list, testing_df)

CPU times: user 3min 20s, sys: 2.8 s, total: 3min 22s
Wall time: 3min 41s

In [32]:
report

,word,average/std,percent_average,percent_std,rating,word_count,divisor,percent,time
0,uneven,0.971225,0.000197,0.000203,NaN,NaN,NaN,NaN,2.276651
1,uneven,NaN,NaN,NaN,1.0,1.0,2177.0,0.000459,NaN
2,uneven,NaN,NaN,NaN,2.0,3.0,4527.0,0.000663,NaN
3,uneven,NaN,NaN,NaN,3.0,0.0,8567.0,0.000000,NaN
4,uneven,NaN,NaN,NaN,4.0,3.0,15584.0,0.000193,NaN
5,uneven,NaN,NaN,NaN,5.0,8.0,29081.0,0.000275,NaN
6,uneven,NaN,NaN,NaN,6.0,4.0,61091.0,0.000065,NaN
7,uneven,NaN,NaN,NaN,7.0,16.0,113108.0,0.000141,NaN
8,uneven,NaN,NaN,NaN,8.0,11.0,125466.0,0.000088,NaN
9,uneven,NaN,NaN,NaN,9.0,4.0,70468.0,0.000057,NaN
10,uneven,NaN,NaN,NaN,10.0,1.0,35426.0,0.000028,NaN
0,sent,0.709769,0.000183,0.000257,NaN,NaN,NaN,NaN,2.299777
1,sent,NaN,NaN,NaN,1.0,2.0,2177.0,0.000919,NaN
2,sent,NaN,NaN,NaN,2.0,0.0,4527.0,0.000000,NaN
3,sent,NaN,NaN,NaN,3.0,0.0,8567.0,0.000000,NaN
4,sent,NaN,NaN,NaN,4.0,2.0,15584.0,0.000128,NaN
5,sent,NaN,NaN,NaN,5.0,4.0,29081.0,0.000138,NaN
6,sent,NaN,NaN,NaN,6.0,3.0,61091.0,0.000049,NaN
7,sent,NaN,NaN,NaN,7.0,11.0,113108.0,0.000097,NaN
8,sent,NaN,NaN,NaN,8.0,9.0,125466.0,0.000072,NaN
9,sent,NaN,NaN,NaN,9.0,10.0,70468.0,0.000142,NaN
10,sent,NaN,NaN,NaN,10.0,10.0,35426.0,0.000282,NaN
0,reliant,0.550119,0.000291,0.000528,NaN,NaN,NaN,NaN,2.509645
1,reliant,NaN,NaN,NaN,1.0,4.0,2177.0,0.001837,NaN
2,reliant,NaN,NaN,NaN,2.0,0.0,4527.0,0.000000,NaN
3,reliant,NaN,NaN,NaN,3.0,3.0,8567.0,0.000350,NaN
4,reliant,NaN,NaN,NaN,4.0,0.0,15584.0,0.000000,NaN
5,reliant,NaN,NaN,NaN,5.0,9.0,29081.0,0.000309,NaN
6,reliant,NaN,NaN,NaN,6.0,8.0,61091.0,0.000131,NaN
7,reliant,NaN,NaN,NaN,7.0,13.0,113108.0,0.000115,NaN
...,...,...,...,...,...,...,...,...,...
3,dr,NaN,NaN,NaN,3.0,1.0,8567.0,0.000117,NaN
4,dr,NaN,NaN,NaN,4.0,4.0,15584.0,0.000257,NaN
5,dr,NaN,NaN,NaN,5.0,1.0,29081.0,0.000034,NaN
6,dr,NaN,NaN,NaN,6.0,5.0,61091.0,0.000082,NaN
7,dr,NaN,NaN,NaN,7.0,10.0,113108.0,0.000088,NaN
8,dr,NaN,NaN,NaN,8.0,14.0,125466.0,0.000112,NaN
9,dr,NaN,NaN,NaN,9.0,14.0,70468.0,0.000199,NaN
10,dr,NaN,NaN,NaN,10.0,2.0,35426.0,0.000056,NaN
0,'take,0.776026,0.000311,0.000401,NaN,NaN,NaN,NaN,2.027239
1,'take,NaN,NaN,NaN,1.0,3.0,2177.0,0.001378,NaN
2,'take,NaN,NaN,NaN,2.0,1.0,4527.0,0.000221,NaN
3,'take,NaN,NaN,NaN,3.0,6.0,8567.0,0.000700,NaN
4,'take,NaN,NaN,NaN,4.0,2.0,15584.0,0.000128,NaN
5,'take,NaN,NaN,NaN,5.0,8.0,29081.0,0.000275,NaN
6,'take,NaN,NaN,NaN,6.0,11.0,61091.0,0.000180,NaN
7,'take,NaN,NaN,NaN,7.0,10.0,113108.0,0.000088,NaN
8,'take,NaN,NaN,NaN,8.0,9.0,125466.0,0.000072,NaN
9,'take,NaN,NaN,NaN,9.0,1.0,70468.0,0.000014,NaN
10,'take,NaN,NaN,NaN,10.0,2.0,35426.0,0.000056,NaN
0,stabbing,1.148149,0.000141,0.000122,NaN,NaN,NaN,NaN,2.021232
1,stabbing,NaN,NaN,NaN,1.0,1.0,2177.0,0.000459,NaN
2,stabbing,NaN,NaN,NaN,2.0,1.0,4527.0,0.000221,NaN
3,stabbing,NaN,NaN,NaN,3.0,0.0,8567.0,0.000000,NaN
4,stabbing,NaN,NaN,NaN,4.0,1.0,15584.0,0.000064,NaN
5,stabbing,NaN,NaN,NaN,5.0,4.0,29081.0,0.000138,NaN
6,stabbing,NaN,NaN,NaN,6.0,8.0,61091.0,0.000131,NaN
7,stabbing,NaN,NaN,NaN,7.0,7.0,113108.0,0.000062,NaN
8,stabbing,NaN,NaN,NaN,8.0,22.0,125466.0,0.000175,NaN
9,stabbing,NaN,NaN,NaN,9.0,7.0,70468.0,0.000099,NaN
10,stabbing,NaN,NaN,NaN,10.0,2.0,35426.0,0.000056,NaN

In [33]:
def write_csv(low, high, df):
    df.to_csv('new_report_for_{}_to_{}.csv'.format(low, high))

In [34]:
def loop_write_report(dictionary, dataframe, number, count):
    num = int(number)
    size = int(count)
    first = 0
    while first < num - 1:
        if first + size < num - 2:
            report = make_report(first, first + size, dictionary, dataframe)
            write_csv(first, first + size, report)
            print('dataframe written from {} to {}'.format(first, first + size))
            first = first + size + 1
        else:
            report = make_report(first, num - 1, dictionary, dataframe)
            write_csv(first, num - 1, report)
            print('dataframe written from {} to {}'.format(first, num - 1))
            print('last dataframe')
            break

In [35]:
loop_write_report(dictionary=dict_list, dataframe=testing_df, number=len(dict_list), count=200)

dataframe written from 0 to 200
dataframe written from 201 to 401
dataframe written from 402 to 602
dataframe written from 603 to 803
dataframe written from 804 to 1004
dataframe written from 1005 to 1205
dataframe written from 1206 to 1406
dataframe written from 1407 to 1607
dataframe written from 1608 to 1808
dataframe written from 1809 to 2009
dataframe written from 2010 to 2210
dataframe written from 2211 to 2411
dataframe written from 2412 to 2612
dataframe written from 2613 to 2813
dataframe written from 2814 to 3014
dataframe written from 3015 to 3215
dataframe written from 3216 to 3416
dataframe written from 3417 to 3617
dataframe written from 3618 to 3818
dataframe written from 3819 to 4019
dataframe written from 4020 to 4220
dataframe written from 4221 to 4421
dataframe written from 4422 to 4622
dataframe written from 4623 to 4670
last dataframe